local _, ns = ...
ns.calMap = {
  [1] = { ["month"] = "Vendémiaire", ["day"] = "1er", ["flavour"] = "du raisin" },
  [2] = { ["month"] = "Vendémiaire", ["day"] = "2", ["flavour"] = "du safran" },
  [3] = { ["month"] = "Vendémiaire", ["day"] = "3", ["flavour"] = "de la châtaigne" },
  [4] = { ["month"] = "Vendémiaire", ["day"] = "4", ["flavour"] = "du colchique" },
  [5] = { ["month"] = "Vendémiaire", ["day"] = "5", ["flavour"] = "du cheval" },
  [6] = { ["month"] = "Vendémiaire", ["day"] = "6", ["flavour"] = "de la balsamine" },
  [7] = { ["month"] = "Vendémiaire", ["day"] = "7", ["flavour"] = "de la carotte" },
  [8] = { ["month"] = "Vendémiaire", ["day"] = "8", ["flavour"] = "de l'amarante" },
  [9] = { ["month"] = "Vendémiaire", ["day"] = "9", ["flavour"] = "du panais" },
  [10] = { ["month"] = "Vendémiaire", ["day"] = "10", ["flavour"] = "de la cuve" },
  [11] = { ["month"] = "Vendémiaire", ["day"] = "11", ["flavour"] = "de la pomme de terre" },
  [12] = { ["month"] = "Vendémiaire", ["day"] = "12", ["flavour"] = "de l'immortelle" },
  [13] = { ["month"] = "Vendémiaire", ["day"] = "13", ["flavour"] = "du potiron" },
  [14] = { ["month"] = "Vendémiaire", ["day"] = "14", ["flavour"] = "du réséda" },
  [15] = { ["month"] = "Vendémiaire", ["day"] = "15", ["flavour"] = "de l'âne" },
  [16] = { ["month"] = "Vendémiaire", ["day"] = "16", ["flavour"] = "de la belle-de-nuit" },
  [17] = { ["month"] = "Vendémiaire", ["day"] = "17", ["flavour"] = "de la citrouille" },
  [18] = { ["month"] = "Vendémiaire", ["day"] = "18", ["flavour"] = "du sarrasin" },
  [19] = { ["month"] = "Vendémiaire", ["day"] = "19", ["flavour"] = "du tournesol" },
  [20] = { ["month"] = "Vendémiaire", ["day"] = "20", ["flavour"] = "du pressoir" },
  [21] = { ["month"] = "Vendémiaire", ["day"] = "21", ["flavour"] = "du chanvre" },
  [22] = { ["month"] = "Vendémiaire", ["day"] = "22", ["flavour"] = "de la pêche" },
  [23] = { ["month"] = "Vendémiaire", ["day"] = "23", ["flavour"] = "du navet" },
  [24] = { ["month"] = "Vendémiaire", ["day"] = "24", ["flavour"] = "de l'amaryllis" },
  [25] = { ["month"] = "Vendémiaire", ["day"] = "25", ["flavour"] = "du bœuf" },
  [26] = { ["month"] = "Vendémiaire", ["day"] = "26", ["flavour"] = "de l'aubergine" },
  [27] = { ["month"] = "Vendémiaire", ["day"] = "27", ["flavour"] = "du piment" },
  [28] = { ["month"] = "Vendémiaire", ["day"] = "28", ["flavour"] = "de la tomate" },
  [29] = { ["month"] = "Vendémiaire", ["day"] = "29", ["flavour"] = "de l'orge" },
  [30] = { ["month"] = "Vendémiaire", ["day"] = "30", ["flavour"] = "du tonneau" },
  [31] = { ["month"] = "Brumaire", ["day"] = "1er", ["flavour"] = "de la pomme" },
  [32] = { ["month"] = "Brumaire", ["day"] = "2", ["flavour"] = "du céleri" },
  [33] = { ["month"] = "Brumaire", ["day"] = "3", ["flavour"] = "de la poire" },
  [34] = { ["month"] = "Brumaire", ["day"] = "4", ["flavour"] = "de la betterave" },
  [35] = { ["month"] = "Brumaire", ["day"] = "5", ["flavour"] = "de l'oie" },
  [36] = { ["month"] = "Brumaire", ["day"] = "6", ["flavour"] = "de l'héliotrope" },
  [37] = { ["month"] = "Brumaire", ["day"] = "7", ["flavour"] = "de la figue" },
  [38] = { ["month"] = "Brumaire", ["day"] = "8", ["flavour"] = "de la scorsonère" },
  [39] = { ["month"] = "Brumaire", ["day"] = "9", ["flavour"] = "de l'alisier" },
  [40] = { ["month"] = "Brumaire", ["day"] = "10", ["flavour"] = "de la charrue" },
  [41] = { ["month"] = "Brumaire", ["day"] = "11", ["flavour"] = "du salsifis" },
  [42] = { ["month"] = "Brumaire", ["day"] = "12", ["flavour"] = "du mâcre" },
  [43] = { ["month"] = "Brumaire", ["day"] = "13", ["flavour"] = "du topinambour" },
  [44] = { ["month"] = "Brumaire", ["day"] = "14", ["flavour"] = "de l'endive" },
  [45] = { ["month"] = "Brumaire", ["day"] = "15", ["flavour"] = "du dindon" },
  [46] = { ["month"] = "Brumaire", ["day"] = "16", ["flavour"] = "du chervis" },
  [47] = { ["month"] = "Brumaire", ["day"] = "17", ["flavour"] = "du cresson" },
  [48] = { ["month"] = "Brumaire", ["day"] = "18", ["flavour"] = "de la dentelaire" },
  [49] = { ["month"] = "Brumaire", ["day"] = "19", ["flavour"] = "de la grenade" },
  [50] = { ["month"] = "Brumaire", ["day"] = "20", ["flavour"] = "de l'herse" },
  [51] = { ["month"] = "Brumaire", ["day"] = "21", ["flavour"] = "de la bacchante" },
  [52] = { ["month"] = "Brumaire", ["day"] = "22", ["flavour"] = "de l'azerole" },
  [53] = { ["month"] = "Brumaire", ["day"] = "23", ["flavour"] = "de la garance" },
  [54] = { ["month"] = "Brumaire", ["day"] = "24", ["flavour"] = "de l'orange" },
  [55] = { ["month"] = "Brumaire", ["day"] = "25", ["flavour"] = "du faisan" },
  [56] = { ["month"] = "Brumaire", ["day"] = "26", ["flavour"] = "de la pistache" },
  [57] = { ["month"] = "Brumaire", ["day"] = "27", ["flavour"] = "du macjonc" },
  [58] = { ["month"] = "Brumaire", ["day"] = "28", ["flavour"] = "du coing" },
  [59] = { ["month"] = "Brumaire", ["day"] = "29", ["flavour"] = "du cormier" },
  [60] = { ["month"] = "Brumaire", ["day"] = "30", ["flavour"] = "du rouleau" },
  [61] = { ["month"] = "Frimaire", ["day"] = "1er", ["flavour"] = "de la raiponce" },
  [62] = { ["month"] = "Frimaire", ["day"] = "2", ["flavour"] = "du turneps" },
  [63] = { ["month"] = "Frimaire", ["day"] = "3", ["flavour"] = "de la chicorée" },
  [64] = { ["month"] = "Frimaire", ["day"] = "4", ["flavour"] = "de la nèfle" },
  [65] = { ["month"] = "Frimaire", ["day"] = "5", ["flavour"] = "du cochon" },
  [66] = { ["month"] = "Frimaire", ["day"] = "6", ["flavour"] = "de la mâche" },
  [67] = { ["month"] = "Frimaire", ["day"] = "7", ["flavour"] = "du chou-fleur" },
  [68] = { ["month"] = "Frimaire", ["day"] = "8", ["flavour"] = "du miel" },
  [69] = { ["month"] = "Frimaire", ["day"] = "9", ["flavour"] = "du genièvre" },
  [70] = { ["month"] = "Frimaire", ["day"] = "10", ["flavour"] = "de la pioche" },
  [71] = { ["month"] = "Frimaire", ["day"] = "11", ["flavour"] = "de la cire" },
  [72] = { ["month"] = "Frimaire", ["day"] = "12", ["flavour"] = "du raifort" },
  [73] = { ["month"] = "Frimaire", ["day"] = "13", ["flavour"] = "du cèdre" },
  [74] = { ["month"] = "Frimaire", ["day"] = "14", ["flavour"] = "du sapin" },
  [75] = { ["month"] = "Frimaire", ["day"] = "15", ["flavour"] = "de la chevre" },
  [76] = { ["month"] = "Frimaire", ["day"] = "16", ["flavour"] = "de l'ajonc" },
  [77] = { ["month"] = "Frimaire", ["day"] = "17", ["flavour"] = "du cyprès" },
  [78] = { ["month"] = "Frimaire", ["day"] = "18", ["flavour"] = "du lierre" },
  [79] = { ["month"] = "Frimaire", ["day"] = "19", ["flavour"] = "de la sabine" },
  [80] = { ["month"] = "Frimaire", ["day"] = "20", ["flavour"] = "du hoyau" },
  [81] = { ["month"] = "Frimaire", ["day"] = "21", ["flavour"] = "de l'érable à sucre" },
  [82] = { ["month"] = "Frimaire", ["day"] = "22", ["flavour"] = "de la bruyère" },
  [83] = { ["month"] = "Frimaire", ["day"] = "23", ["flavour"] = "du roseau" },
  [84] = { ["month"] = "Frimaire", ["day"] = "24", ["flavour"] = "de l'oseille" },
  [85] = { ["month"] = "Frimaire", ["day"] = "25", ["flavour"] = "du grillon" },
  [86] = { ["month"] = "Frimaire", ["day"] = "26", ["flavour"] = "du pignon" },
  [87] = { ["month"] = "Frimaire", ["day"] = "27", ["flavour"] = "du liège" },
  [88] = { ["month"] = "Frimaire", ["day"] = "28", ["flavour"] = "de la truffe" },
  [89] = { ["month"] = "Frimaire", ["day"] = "29", ["flavour"] = "de l'olive" },
  [90] = { ["month"] = "Frimaire", ["day"] = "30", ["flavour"] = "de la pelle" },
  [91] = { ["month"] = "Nivôse", ["day"] = "1er", ["flavour"] = "de la tourbe" },
  [92] = { ["month"] = "Nivôse", ["day"] = "2", ["flavour"] = "de la houille" },
  [93] = { ["month"] = "Nivôse", ["day"] = "3", ["flavour"] = "du bitume" },
  [94] = { ["month"] = "Nivôse", ["day"] = "4", ["flavour"] = "du soufre" },
  [95] = { ["month"] = "Nivôse", ["day"] = "5", ["flavour"] = "du chien" },
  [96] = { ["month"] = "Nivôse", ["day"] = "6", ["flavour"] = "de la lave" },
  [97] = { ["month"] = "Nivôse", ["day"] = "7", ["flavour"] = "de la terre végétale" },
  [98] = { ["month"] = "Nivôse", ["day"] = "8", ["flavour"] = "du fumier" },
  [99] = { ["month"] = "Nivôse", ["day"] = "9", ["flavour"] = "du salpêtre" },
  [100] = { ["month"] = "Nivôse", ["day"] = "10", ["flavour"] = "du fléau" },
  [101] = { ["month"] = "Nivôse", ["day"] = "11", ["flavour"] = "du granit" },
  [102] = { ["month"] = "Nivôse", ["day"] = "12", ["flavour"] = "de l'argile" },
  [103] = { ["month"] = "Nivôse", ["day"] = "13", ["flavour"] = "de l'ardoise" },
  [104] = { ["month"] = "Nivôse", ["day"] = "14", ["flavour"] = "du grès" },
  [105] = { ["month"] = "Nivôse", ["day"] = "15", ["flavour"] = "du lapin" },
  [106] = { ["month"] = "Nivôse", ["day"] = "16", ["flavour"] = "du silex" },
  [107] = { ["month"] = "Nivôse", ["day"] = "17", ["flavour"] = "de la marne" },
  [108] = { ["month"] = "Nivôse", ["day"] = "18", ["flavour"] = "de la pierre à chaux" },
  [109] = { ["month"] = "Nivôse", ["day"] = "19", ["flavour"] = "du marbre" },
  [110] = { ["month"] = "Nivôse", ["day"] = "20", ["flavour"] = "du van" },
  [111] = { ["month"] = "Nivôse", ["day"] = "21", ["flavour"] = "de la pierre à plâtre" },
  [112] = { ["month"] = "Nivôse", ["day"] = "22", ["flavour"] = "du sel" },
  [113] = { ["month"] = "Nivôse", ["day"] = "23", ["flavour"] = "du fer" },
  [114] = { ["month"] = "Nivôse", ["day"] = "24", ["flavour"] = "du cuivre" },
  [115] = { ["month"] = "Nivôse", ["day"] = "25", ["flavour"] = "du chat" },
  [116] = { ["month"] = "Nivôse", ["day"] = "26", ["flavour"] = "de l'étain" },
  [117] = { ["month"] = "Nivôse", ["day"] = "27", ["flavour"] = "du plomb" },
  [118] = { ["month"] = "Nivôse", ["day"] = "28", ["flavour"] = "du zinc" },
  [119] = { ["month"] = "Nivôse", ["day"] = "29", ["flavour"] = "du mercure" },
  [120] = { ["month"] = "Nivôse", ["day"] = "30", ["flavour"] = "du crible" },
  [121] = { ["month"] = "Pluviôse", ["day"] = "1er", ["flavour"] = "de la lauréole" },
  [122] = { ["month"] = "Pluviôse", ["day"] = "2", ["flavour"] = "de la mousse" },
  [123] = { ["month"] = "Pluviôse", ["day"] = "3", ["flavour"] = "du fragon" },
  [124] = { ["month"] = "Pluviôse", ["day"] = "4", ["flavour"] = "du perce-neige" },
  [125] = { ["month"] = "Pluviôse", ["day"] = "5", ["flavour"] = "du taureau" },
  [126] = { ["month"] = "Pluviôse", ["day"] = "6", ["flavour"] = "du laurier-thym" },
  [127] = { ["month"] = "Pluviôse", ["day"] = "7", ["flavour"] = "de l'amadouvier" },
  [128] = { ["month"] = "Pluviôse", ["day"] = "8", ["flavour"] = "du mézéréon" },
  [129] = { ["month"] = "Pluviôse", ["day"] = "9", ["flavour"] = "du peuplier" },
  [130] = { ["month"] = "Pluviôse", ["day"] = "10", ["flavour"] = "de la cognée" },
  [131] = { ["month"] = "Pluviôse", ["day"] = "11", ["flavour"] = "de l'ellébore" },
  [132] = { ["month"] = "Pluviôse", ["day"] = "12", ["flavour"] = "du brocoli" },
  [133] = { ["month"] = "Pluviôse", ["day"] = "13", ["flavour"] = "du laurier" },
  [134] = { ["month"] = "Pluviôse", ["day"] = "14", ["flavour"] = "de l'avelinier" },
  [135] = { ["month"] = "Pluviôse", ["day"] = "15", ["flavour"] = "de la vache" },
  [136] = { ["month"] = "Pluviôse", ["day"] = "16", ["flavour"] = "du buis" },
  [137] = { ["month"] = "Pluviôse", ["day"] = "17", ["flavour"] = "du lichen" },
  [138] = { ["month"] = "Pluviôse", ["day"] = "18", ["flavour"] = "de l'if" },
  [139] = { ["month"] = "Pluviôse", ["day"] = "19", ["flavour"] = "de la pulmonaire" },
  [140] = { ["month"] = "Pluviôse", ["day"] = "20", ["flavour"] = "de la serpette" },
  [141] = { ["month"] = "Pluviôse", ["day"] = "21", ["flavour"] = "du thlaspi" },
  [142] = { ["month"] = "Pluviôse", ["day"] = "22", ["flavour"] = "du thymèle" },
  [143] = { ["month"] = "Pluviôse", ["day"] = "23", ["flavour"] = "du chiendent" },
  [144] = { ["month"] = "Pluviôse", ["day"] = "24", ["flavour"] = "de la trainasse" },
  [145] = { ["month"] = "Pluviôse", ["day"] = "25", ["flavour"] = "du lièvre" },
  [146] = { ["month"] = "Pluviôse", ["day"] = "26", ["flavour"] = "du guède" },
  [147] = { ["month"] = "Pluviôse", ["day"] = "27", ["flavour"] = "du noisetier" },
  [148] = { ["month"] = "Pluviôse", ["day"] = "28", ["flavour"] = "du cyclamen" },
  [149] = { ["month"] = "Pluviôse", ["day"] = "29", ["flavour"] = "de la chélidoine" },
  [150] = { ["month"] = "Pluviôse", ["day"] = "30", ["flavour"] = "du traîneau" },
  [151] = { ["month"] = "Ventôse", ["day"] = "1er", ["flavour"] = "du tussilage" },
  [152] = { ["month"] = "Ventôse", ["day"] = "2", ["flavour"] = "du cornouiller" },
  [153] = { ["month"] = "Ventôse", ["day"] = "3", ["flavour"] = "du violier" },
  [154] = { ["month"] = "Ventôse", ["day"] = "4", ["flavour"] = "du troène" },
  [155] = { ["month"] = "Ventôse", ["day"] = "5", ["flavour"] = "du bouc" },
  [156] = { ["month"] = "Ventôse", ["day"] = "6", ["flavour"] = "de l'asaret" },
  [157] = { ["month"] = "Ventôse", ["day"] = "7", ["flavour"] = "de l'alaterne" },
  [158] = { ["month"] = "Ventôse", ["day"] = "8", ["flavour"] = "de la violette" },
  [159] = { ["month"] = "Ventôse", ["day"] = "9", ["flavour"] = "du marceau" },
  [160] = { ["month"] = "Ventôse", ["day"] = "10", ["flavour"] = "de la bêche" },
  [161] = { ["month"] = "Ventôse", ["day"] = "11", ["flavour"] = "du narcisse" },
  [162] = { ["month"] = "Ventôse", ["day"] = "12", ["flavour"] = "de l'orme" },
  [163] = { ["month"] = "Ventôse", ["day"] = "13", ["flavour"] = "de la fumeterre" },
  [164] = { ["month"] = "Ventôse", ["day"] = "14", ["flavour"] = "du vélar" },
  [165] = { ["month"] = "Ventôse", ["day"] = "15", ["flavour"] = "de la chèvre" },
  [166] = { ["month"] = "Ventôse", ["day"] = "16", ["flavour"] = "de l'épinard" },
  [167] = { ["month"] = "Ventôse", ["day"] = "17", ["flavour"] = "du doronic" },
  [168] = { ["month"] = "Ventôse", ["day"] = "18", ["flavour"] = "du mouron" },
  [169] = { ["month"] = "Ventôse", ["day"] = "19", ["flavour"] = "du cerfeuil" },
  [170] = { ["month"] = "Ventôse", ["day"] = "20", ["flavour"] = "du cordeau" },
  [171] = { ["month"] = "Ventôse", ["day"] = "21", ["flavour"] = "de la mandragore" },
  [172] = { ["month"] = "Ventôse", ["day"] = "22", ["flavour"] = "du persil" },
  [173] = { ["month"] = "Ventôse", ["day"] = "23", ["flavour"] = "de la cochléaria" },
  [174] = { ["month"] = "Ventôse", ["day"] = "24", ["flavour"] = "de la pâquerette" },
  [175] = { ["month"] = "Ventôse", ["day"] = "25", ["flavour"] = "du thon" },
  [176] = { ["month"] = "Ventôse", ["day"] = "26", ["flavour"] = "du pissenlit" },
  [177] = { ["month"] = "Ventôse", ["day"] = "27", ["flavour"] = "de la sylvie" },
  [178] = { ["month"] = "Ventôse", ["day"] = "28", ["flavour"] = "de la capillaire" },
  [179] = { ["month"] = "Ventôse", ["day"] = "29", ["flavour"] = "du frêne" },
  [180] = { ["month"] = "Ventôse", ["day"] = "30", ["flavour"] = "du plantoir" },
  [181] = { ["month"] = "Germinal", ["day"] = "1er", ["flavour"] = "du primevère" },
  [182] = { ["month"] = "Germinal", ["day"] = "2", ["flavour"] = "du platane" },
  [183] = { ["month"] = "Germinal", ["day"] = "3", ["flavour"] = "de l'asperge" },
  [184] = { ["month"] = "Germinal", ["day"] = "4", ["flavour"] = "de la tulipe" },
  [185] = { ["month"] = "Germinal", ["day"] = "5", ["flavour"] = "de la poule" },
  [186] = { ["month"] = "Germinal", ["day"] = "6", ["flavour"] = "de la bette" },
  [187] = { ["month"] = "Germinal", ["day"] = "7", ["flavour"] = "du bouleau" },
  [188] = { ["month"] = "Germinal", ["day"] = "8", ["flavour"] = "de la jonquille" },
  [189] = { ["month"] = "Germinal", ["day"] = "9", ["flavour"] = "de l'aulne" },
  [190] = { ["month"] = "Germinal", ["day"] = "10", ["flavour"] = "du couvoir" },
  [191] = { ["month"] = "Germinal", ["day"] = "11", ["flavour"] = "de la pervenche" },
  [192] = { ["month"] = "Germinal", ["day"] = "12", ["flavour"] = "du charme" },
  [193] = { ["month"] = "Germinal", ["day"] = "13", ["flavour"] = "de la morille" },
  [194] = { ["month"] = "Germinal", ["day"] = "14", ["flavour"] = "du hêtre" },
  [195] = { ["month"] = "Germinal", ["day"] = "15", ["flavour"] = "de l'abeille" },
  [196] = { ["month"] = "Germinal", ["day"] = "16", ["flavour"] = "de la laitue" },
  [197] = { ["month"] = "Germinal", ["day"] = "17", ["flavour"] = "du mélèze" },
  [198] = { ["month"] = "Germinal", ["day"] = "18", ["flavour"] = "de la ciguë" },
  [199] = { ["month"] = "Germinal", ["day"] = "19", ["flavour"] = "du radis" },
  [200] = { ["month"] = "Germinal", ["day"] = "20", ["flavour"] = "de la ruche" },
  [201] = { ["month"] = "Germinal", ["day"] = "21", ["flavour"] = "du gainier" },
  [202] = { ["month"] = "Germinal", ["day"] = "22", ["flavour"] = "de la romaine" },
  [203] = { ["month"] = "Germinal", ["day"] = "23", ["flavour"] = "du marronnier" },
  [204] = { ["month"] = "Germinal", ["day"] = "24", ["flavour"] = "de la roquette" },
  [205] = { ["month"] = "Germinal", ["day"] = "25", ["flavour"] = "du pigeon" },
  [206] = { ["month"] = "Germinal", ["day"] = "26", ["flavour"] = "du lilas" },
  [207] = { ["month"] = "Germinal", ["day"] = "27", ["flavour"] = "de l'anémone" },
  [208] = { ["month"] = "Germinal", ["day"] = "28", ["flavour"] = "de la pensée" },
  [209] = { ["month"] = "Germinal", ["day"] = "29", ["flavour"] = "de la myrtille" },
  [210] = { ["month"] = "Germinal", ["day"] = "30", ["flavour"] = "du greffoir" },
  [211] = { ["month"] = "Floréal", ["day"] = "1er", ["flavour"] = "de la rose" },
  [212] = { ["month"] = "Floréal", ["day"] = "2", ["flavour"] = "du chêne" },
  [213] = { ["month"] = "Floréal", ["day"] = "3", ["flavour"] = "de la fougère" },
  [214] = { ["month"] = "Floréal", ["day"] = "4", ["flavour"] = "de l'aubépine" },
  [215] = { ["month"] = "Floréal", ["day"] = "5", ["flavour"] = "du rossignol" },
  [216] = { ["month"] = "Floréal", ["day"] = "6", ["flavour"] = "de l'ancolie" },
  [217] = { ["month"] = "Floréal", ["day"] = "7", ["flavour"] = "du muguet" },
  [218] = { ["month"] = "Floréal", ["day"] = "8", ["flavour"] = "du champignon" },
  [219] = { ["month"] = "Floréal", ["day"] = "9", ["flavour"] = "de l'hyacinthe" },
  [220] = { ["month"] = "Floréal", ["day"] = "10", ["flavour"] = "du râteau" },
  [221] = { ["month"] = "Floréal", ["day"] = "11", ["flavour"] = "de la rhubarbe" },
  [222] = { ["month"] = "Floréal", ["day"] = "12", ["flavour"] = "du sainfoin" },
  [223] = { ["month"] = "Floréal", ["day"] = "13", ["flavour"] = "du bâton-d'or" },
  [224] = { ["month"] = "Floréal", ["day"] = "14", ["flavour"] = "du chamérisier" },
  [225] = { ["month"] = "Floréal", ["day"] = "15", ["flavour"] = "du ver à soie" },
  [226] = { ["month"] = "Floréal", ["day"] = "16", ["flavour"] = "de la consoude" },
  [227] = { ["month"] = "Floréal", ["day"] = "17", ["flavour"] = "de la pimprenelle" },
  [228] = { ["month"] = "Floréal", ["day"] = "18", ["flavour"] = "de la corbeille d'or" },
  [229] = { ["month"] = "Floréal", ["day"] = "19", ["flavour"] = "de l'arroche" },
  [230] = { ["month"] = "Floréal", ["day"] = "20", ["flavour"] = "du sarcloir" },
  [231] = { ["month"] = "Floréal", ["day"] = "21", ["flavour"] = "du statice" },
  [232] = { ["month"] = "Floréal", ["day"] = "22", ["flavour"] = "de la fritillaire" },
  [233] = { ["month"] = "Floréal", ["day"] = "23", ["flavour"] = "de la bourrache" },
  [234] = { ["month"] = "Floréal", ["day"] = "24", ["flavour"] = "de la valériane" },
  [235] = { ["month"] = "Floréal", ["day"] = "25", ["flavour"] = "de la carpe" },
  [236] = { ["month"] = "Floréal", ["day"] = "26", ["flavour"] = "du fusain" },
  [237] = { ["month"] = "Floréal", ["day"] = "27", ["flavour"] = "de la civette" },
  [238] = { ["month"] = "Floréal", ["day"] = "28", ["flavour"] = "de la buglosse" },
  [239] = { ["month"] = "Floréal", ["day"] = "29", ["flavour"] = "du sénevé" },
  [240] = { ["month"] = "Floréal", ["day"] = "30", ["flavour"] = "de la houlette" },
  [241] = { ["month"] = "Prairial", ["day"] = "1er", ["flavour"] = "de la luzerne" },
  [242] = { ["month"] = "Prairial", ["day"] = "2", ["flavour"] = "de l'hémérocalle" },
  [243] = { ["month"] = "Prairial", ["day"] = "3", ["flavour"] = "du trèfle" },
  [244] = { ["month"] = "Prairial", ["day"] = "4", ["flavour"] = "de l'angélique" },
  [245] = { ["month"] = "Prairial", ["day"] = "5", ["flavour"] = "du canard" },
  [246] = { ["month"] = "Prairial", ["day"] = "6", ["flavour"] = "de la mélisse" },
  [247] = { ["month"] = "Prairial", ["day"] = "7", ["flavour"] = "du fromental" },
  [248] = { ["month"] = "Prairial", ["day"] = "8", ["flavour"] = "du martagon" },
  [249] = { ["month"] = "Prairial", ["day"] = "9", ["flavour"] = "du serpolet" },
  [250] = { ["month"] = "Prairial", ["day"] = "10", ["flavour"] = "du faux" },
  [251] = { ["month"] = "Prairial", ["day"] = "11", ["flavour"] = "de la fraise" },
  [252] = { ["month"] = "Prairial", ["day"] = "12", ["flavour"] = "de la bétoine" },
  [253] = { ["month"] = "Prairial", ["day"] = "13", ["flavour"] = "du pois" },
  [254] = { ["month"] = "Prairial", ["day"] = "14", ["flavour"] = "de l'acacia" },
  [255] = { ["month"] = "Prairial", ["day"] = "15", ["flavour"] = "de la caille" },
  [256] = { ["month"] = "Prairial", ["day"] = "16", ["flavour"] = "de l'œillet" },
  [257] = { ["month"] = "Prairial", ["day"] = "17", ["flavour"] = "du sureau" },
  [258] = { ["month"] = "Prairial", ["day"] = "18", ["flavour"] = "du pavot" },
  [259] = { ["month"] = "Prairial", ["day"] = "19", ["flavour"] = "du tilleul" },
  [260] = { ["month"] = "Prairial", ["day"] = "20", ["flavour"] = "de la fourche" },
  [261] = { ["month"] = "Prairial", ["day"] = "21", ["flavour"] = "du barbeau" },
  [262] = { ["month"] = "Prairial", ["day"] = "22", ["flavour"] = "de la camomille" },
  [263] = { ["month"] = "Prairial", ["day"] = "23", ["flavour"] = "du chèvrefeuille" },
  [264] = { ["month"] = "Prairial", ["day"] = "24", ["flavour"] = "du caille-lait" },
  [265] = { ["month"] = "Prairial", ["day"] = "25", ["flavour"] = "de la tanche" },
  [266] = { ["month"] = "Prairial", ["day"] = "26", ["flavour"] = "du jasmin" },
  [267] = { ["month"] = "Prairial", ["day"] = "27", ["flavour"] = "de la verveine" },
  [268] = { ["month"] = "Prairial", ["day"] = "28", ["flavour"] = "du thym" },
  [269] = { ["month"] = "Prairial", ["day"] = "29", ["flavour"] = "de la pivoine" },
  [270] = { ["month"] = "Prairial", ["day"] = "30", ["flavour"] = "du chariot" },
  [271] = { ["month"] = "Messidor", ["day"] = "1er", ["flavour"] = "du seigle" },
  [272] = { ["month"] = "Messidor", ["day"] = "2", ["flavour"] = "de l'avoine" },
  [273] = { ["month"] = "Messidor", ["day"] = "3", ["flavour"] = "de l'oignon" },
  [274] = { ["month"] = "Messidor", ["day"] = "4", ["flavour"] = "de la véronique" },
  [275] = { ["month"] = "Messidor", ["day"] = "5", ["flavour"] = "du mulet" },
  [276] = { ["month"] = "Messidor", ["day"] = "6", ["flavour"] = "du romarin" },
  [277] = { ["month"] = "Messidor", ["day"] = "7", ["flavour"] = "du concombre" },
  [278] = { ["month"] = "Messidor", ["day"] = "8", ["flavour"] = "de l'échalote" },
  [279] = { ["month"] = "Messidor", ["day"] = "9", ["flavour"] = "de l'absinthe" },
  [280] = { ["month"] = "Messidor", ["day"] = "10", ["flavour"] = "de la faucille" },
  [281] = { ["month"] = "Messidor", ["day"] = "11", ["flavour"] = "de la coriandre" },
  [282] = { ["month"] = "Messidor", ["day"] = "12", ["flavour"] = "de l'artichaut" },
  [283] = { ["month"] = "Messidor", ["day"] = "13", ["flavour"] = "de la giroflée" },
  [284] = { ["month"] = "Messidor", ["day"] = "14", ["flavour"] = "de la lavande" },
  [285] = { ["month"] = "Messidor", ["day"] = "15", ["flavour"] = "du chamois" },
  [286] = { ["month"] = "Messidor", ["day"] = "16", ["flavour"] = "du tabac" },
  [287] = { ["month"] = "Messidor", ["day"] = "17", ["flavour"] = "de la groseille" },
  [288] = { ["month"] = "Messidor", ["day"] = "18", ["flavour"] = "de la gesse" },
  [289] = { ["month"] = "Messidor", ["day"] = "19", ["flavour"] = "de la cerise" },
  [290] = { ["month"] = "Messidor", ["day"] = "20", ["flavour"] = "du parc" },
  [291] = { ["month"] = "Messidor", ["day"] = "21", ["flavour"] = "de la menthe" },
  [292] = { ["month"] = "Messidor", ["day"] = "22", ["flavour"] = "du cumin" },
  [293] = { ["month"] = "Messidor", ["day"] = "23", ["flavour"] = "de l'haricot" },
  [294] = { ["month"] = "Messidor", ["day"] = "24", ["flavour"] = "de l'orcanète" },
  [295] = { ["month"] = "Messidor", ["day"] = "25", ["flavour"] = "de la pintade" },
  [296] = { ["month"] = "Messidor", ["day"] = "26", ["flavour"] = "de la sauge" },
  [297] = { ["month"] = "Messidor", ["day"] = "27", ["flavour"] = "de l'ail" },
  [298] = { ["month"] = "Messidor", ["day"] = "28", ["flavour"] = "de la vesce" },
  [299] = { ["month"] = "Messidor", ["day"] = "29", ["flavour"] = "du blé" },
  [300] = { ["month"] = "Messidor", ["day"] = "30", ["flavour"] = "de la chalemie" },
  [301] = { ["month"] = "Thermidor", ["day"] = "1er", ["flavour"] = "de l'épeautre" },
  [302] = { ["month"] = "Thermidor", ["day"] = "2", ["flavour"] = "du bouillon-blanc" },
  [303] = { ["month"] = "Thermidor", ["day"] = "3", ["flavour"] = "du melon" },
  [304] = { ["month"] = "Thermidor", ["day"] = "4", ["flavour"] = "de l'ivraie" },
  [305] = { ["month"] = "Thermidor", ["day"] = "5", ["flavour"] = "du bélier" },
  [306] = { ["month"] = "Thermidor", ["day"] = "6", ["flavour"] = "de la prêle" },
  [307] = { ["month"] = "Thermidor", ["day"] = "7", ["flavour"] = "de l'armoise" },
  [308] = { ["month"] = "Thermidor", ["day"] = "8", ["flavour"] = "du carthame" },
  [309] = { ["month"] = "Thermidor", ["day"] = "9", ["flavour"] = "de la mûre" },
  [310] = { ["month"] = "Thermidor", ["day"] = "10", ["flavour"] = "de l'arrosoir" },
  [311] = { ["month"] = "Thermidor", ["day"] = "11", ["flavour"] = "du panic" },
  [312] = { ["month"] = "Thermidor", ["day"] = "12", ["flavour"] = "de la salicorne" },
  [313] = { ["month"] = "Thermidor", ["day"] = "13", ["flavour"] = "de l'abricot" },
  [314] = { ["month"] = "Thermidor", ["day"] = "14", ["flavour"] = "du basilic" },
  [315] = { ["month"] = "Thermidor", ["day"] = "15", ["flavour"] = "de la brebis" },
  [316] = { ["month"] = "Thermidor", ["day"] = "16", ["flavour"] = "de la guimauve" },
  [317] = { ["month"] = "Thermidor", ["day"] = "17", ["flavour"] = "du lin" },
  [318] = { ["month"] = "Thermidor", ["day"] = "18", ["flavour"] = "de l'amande" },
  [319] = { ["month"] = "Thermidor", ["day"] = "19", ["flavour"] = "de la gentiane" },
  [320] = { ["month"] = "Thermidor", ["day"] = "20", ["flavour"] = "de l'écluse" },
  [321] = { ["month"] = "Thermidor", ["day"] = "21", ["flavour"] = "de la carline" },
  [322] = { ["month"] = "Thermidor", ["day"] = "22", ["flavour"] = "du câprier" },
  [323] = { ["month"] = "Thermidor", ["day"] = "23", ["flavour"] = "de la lentille" },
  [324] = { ["month"] = "Thermidor", ["day"] = "24", ["flavour"] = "de l'aunée" },
  [325] = { ["month"] = "Thermidor", ["day"] = "25", ["flavour"] = "de la loutre" },
  [326] = { ["month"] = "Thermidor", ["day"] = "26", ["flavour"] = "du myrte" },
  [327] = { ["month"] = "Thermidor", ["day"] = "27", ["flavour"] = "du colza" },
  [328] = { ["month"] = "Thermidor", ["day"] = "28", ["flavour"] = "du lupin" },
  [329] = { ["month"] = "Thermidor", ["day"] = "29", ["flavour"] = "du coton" },
  [330] = { ["month"] = "Thermidor", ["day"] = "30", ["flavour"] = "du moulin" },
  [331] = { ["month"] = "Fructidor", ["day"] = "1er", ["flavour"] = "de la prune" },
  [332] = { ["month"] = "Fructidor", ["day"] = "2", ["flavour"] = "du millet" },
  [333] = { ["month"] = "Fructidor", ["day"] = "3", ["flavour"] = "du lycoperdon" },
  [334] = { ["month"] = "Fructidor", ["day"] = "4", ["flavour"] = "de l'escourgeon" },
  [335] = { ["month"] = "Fructidor", ["day"] = "5", ["flavour"] = "du saumon" },
  [336] = { ["month"] = "Fructidor", ["day"] = "6", ["flavour"] = "de la tubéreuse" },
  [337] = { ["month"] = "Fructidor", ["day"] = "7", ["flavour"] = "du sucrion" },
  [338] = { ["month"] = "Fructidor", ["day"] = "8", ["flavour"] = "de l'apocyn" },
  [339] = { ["month"] = "Fructidor", ["day"] = "9", ["flavour"] = "de la réglisse" },
  [340] = { ["month"] = "Fructidor", ["day"] = "10", ["flavour"] = "de l'échelle" },
  [341] = { ["month"] = "Fructidor", ["day"] = "11", ["flavour"] = "de la pastèque" },
  [342] = { ["month"] = "Fructidor", ["day"] = "12", ["flavour"] = "du fenouil" },
  [343] = { ["month"] = "Fructidor", ["day"] = "13", ["flavour"] = "de l'épine-vinette" },
  [344] = { ["month"] = "Fructidor", ["day"] = "14", ["flavour"] = "de la noix" },
  [345] = { ["month"] = "Fructidor", ["day"] = "15", ["flavour"] = "de la truite" },
  [346] = { ["month"] = "Fructidor", ["day"] = "16", ["flavour"] = "du citron" },
  [347] = { ["month"] = "Fructidor", ["day"] = "17", ["flavour"] = "de la cardère" },
  [348] = { ["month"] = "Fructidor", ["day"] = "18", ["flavour"] = "du nerprun" },
  [349] = { ["month"] = "Fructidor", ["day"] = "19", ["flavour"] = "de la tagette" },
  [350] = { ["month"] = "Fructidor", ["day"] = "20", ["flavour"] = "de la hotte" },
  [351] = { ["month"] = "Fructidor", ["day"] = "21", ["flavour"] = "de l'églantier" },
  [352] = { ["month"] = "Fructidor", ["day"] = "22", ["flavour"] = "de la noisette" },
  [353] = { ["month"] = "Fructidor", ["day"] = "23", ["flavour"] = "du houblon" },
  [354] = { ["month"] = "Fructidor", ["day"] = "24", ["flavour"] = "du sorgho" },
  [355] = { ["month"] = "Fructidor", ["day"] = "25", ["flavour"] = "de l'écrevisse" },
  [356] = { ["month"] = "Fructidor", ["day"] = "26", ["flavour"] = "de la bigarade" },
  [357] = { ["month"] = "Fructidor", ["day"] = "27", ["flavour"] = "de la verge d'or" },
  [358] = { ["month"] = "Fructidor", ["day"] = "28", ["flavour"] = "du maïs" },
  [359] = { ["month"] = "Fructidor", ["day"] = "29", ["flavour"] = "du marron" },
  [360] = { ["month"] = "Fructidor", ["day"] = "30", ["flavour"] = "du panier" },
  [361] = { ["name"] = "jour de la Vertu" },
  [362] = { ["name"] = "jour du Génie" },
  [363] = { ["name"] = "jour du Travail" },
  [364] = { ["name"] = "jour de l'Opinion" },
  [365] = { ["name"] = "jour des Récompenses" },
  [366] = { ["name"] = "jour de la Révolution" }
}